"""link transactions to credit cards

Revision ID: 244dfe73397e
Revises: 3b82f4dfe186
Create Date: 2026-09-12 03:24:55.695064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244dfe73397e'
down_revision: Union[str, Sequence[str], None] = '3b82f4dfe186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_card_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_transactions_credit_card_id', 'credit_cards', ['credit_card_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_credit_card_id', type_='foreignkey')
        batch_op.drop_column('credit_card_id')
    # ### end Alembic commands ###
