"""subscription last paid date

Revision ID: 3b82f4dfe186
Revises: eb31f3f10f1b
Create Date: 2026-09-07 15:41:55.227678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b82f4dfe186'
down_revision: Union[str, Sequence[str], None] = 'eb31f3f10f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('last_paid_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'last_paid_date')
    # ### end Alembic commands ###
