"""recurring transactions

Revision ID: 7824d5bad5e9
Revises: f74cf5b0e3ab
Create Date: 2026-09-06 12:55:57.352040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7824d5bad5e9'
down_revision: Union[str, Sequence[str], None] = 'f74cf5b0e3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_transactions_id'), 'recurring_transactions', ['id'], unique=False)
    op.create_index('ix_recurring_transactions_owner_active_due', 'recurring_transactions', ['owner_id', 'is_active', 'next_due_date'], unique=False)
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_transactions_recurring_transaction_id', 'recurring_transactions', ['recurring_transaction_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_recurring_transaction_id', type_='foreignkey')
        batch_op.drop_column('recurring_transaction_id')
    op.drop_index('ix_recurring_transactions_owner_active_due', table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_id'), table_name='recurring_transactions')
    op.drop_table('recurring_transactions')
    # ### end Alembic commands ###
