"""budget limits and performance indexes

Revision ID: f74cf5b0e3ab
Revises: 3fc574a5f29b
Create Date: 2026-08-30 00:11:16.293057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74cf5b0e3ab'
down_revision: Union[str, Sequence[str], None] = '3fc574a5f29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('monthly_limit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_limits_id'), 'budget_limits', ['id'], unique=False)
    op.create_index('ix_budget_limits_owner_category', 'budget_limits', ['owner_id', 'category'], unique=False)
    op.create_index('ix_subscriptions_owner_active_due', 'subscriptions', ['owner_id', 'is_active', 'next_due_date'], unique=False)
    op.create_index('ix_transactions_owner_occurred', 'transactions', ['owner_id', 'occurred_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_owner_occurred', table_name='transactions')
    op.drop_index('ix_subscriptions_owner_active_due', table_name='subscriptions')
    op.drop_index('ix_budget_limits_owner_category', table_name='budget_limits')
    op.drop_index(op.f('ix_budget_limits_id'), table_name='budget_limits')
    op.drop_table('budget_limits')
    # ### end Alembic commands ###
